### PR TITLE
Updated welcome-new-contributors.yml

### PR DESCRIPTION
**Pull request by Night-Amber3301**
Made the required changes

### CODE REVIEW

**Review by Pinaka-Pani-18 — COMMENTED** [review]
Before creating a pull request, please make sure you've requested to work on the respective issue. If I've assigned the issue to you, then you can proceed with your work and submit the pull request.

**Comment by Night-Amber3301** [comment]
My bad but you should've mentioned it in CONTRIBUTING.md that a PR can only be raised if someone is assigned to work on a specific issue.

**Comment by Pinaka-Pani-18** [comment]
Yeah, sorry for that. I need to make an issue on this as well, and also I need to add updated images in the contributing.md file. Also, it's basic: one should comment on the issue they want to work on because if we accept it, there may be a chance that it will again be excluded from Hacktoberfest. Then we both should suffer. So, please kindly make sure to comment on the issue you want to work on. I will assign you to the issue and make a PR.

If you are able to update the contributing.md file with images and required changes, please tell me. I will make an issue, and if you comment, I can assign you to that issue.

**Comment by Night-Amber3301** [comment]
Yeah appreciate it, I would love to contribute

Thanks!

**Pull request closed without merging**
